"""add low stock threshold

Revision ID: 453689d926bf
Revises: 8b645782a1f6
Create Date: 2026-07-20 08:39:32.849892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '453689d926bf'
down_revision: Union[str, Sequence[str], None] = '8b645782a1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
    op.drop_column('products', 'image_public_id')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image_public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'low_stock_threshold')
    op.alter_column('product_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
