"""add product discount fields

Revision ID: fa25fc4a2256
Revises: 848bc70c7c42
Create Date: 2026-08-07 14:16:46.747333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa25fc4a2256'
down_revision: Union[str, Sequence[str], None] = '848bc70c7c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_type', sa.String(), nullable=False, server_default='none'))
    op.add_column('products', sa.Column('discount_value', sa.Float(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('discount_active', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_active')
    op.drop_column('products', 'discount_value')
    op.drop_column('products', 'discount_type')
    # ### end Alembic commands ###
